var annotated_dup =
[
    [ "Nebukam", "namespace_nebukam.html", [
      [ "ORCA", "namespace_nebukam_1_1_o_r_c_a.html", [
        [ "Agent", "class_nebukam_1_1_o_r_c_a_1_1_agent.html", "class_nebukam_1_1_o_r_c_a_1_1_agent" ],
        [ "AgentData", "struct_nebukam_1_1_o_r_c_a_1_1_agent_data.html", null ],
        [ "AgentDataResult", "struct_nebukam_1_1_o_r_c_a_1_1_agent_data_result.html", null ],
        [ "AgentGroup", "class_nebukam_1_1_o_r_c_a_1_1_agent_group.html", null ],
        [ "AgentKDTreeBuilder", "class_nebukam_1_1_o_r_c_a_1_1_agent_k_d_tree_builder.html", "class_nebukam_1_1_o_r_c_a_1_1_agent_k_d_tree_builder" ],
        [ "AgentKDTreeJob", "struct_nebukam_1_1_o_r_c_a_1_1_agent_k_d_tree_job.html", null ],
        [ "AgentKDTreeProcessor", "class_nebukam_1_1_o_r_c_a_1_1_agent_k_d_tree_processor.html", "class_nebukam_1_1_o_r_c_a_1_1_agent_k_d_tree_processor" ],
        [ "AgentProvider", "class_nebukam_1_1_o_r_c_a_1_1_agent_provider.html", "class_nebukam_1_1_o_r_c_a_1_1_agent_provider" ],
        [ "AgentTreeNode", "struct_nebukam_1_1_o_r_c_a_1_1_agent_tree_node.html", null ],
        [ "DVP", "struct_nebukam_1_1_o_r_c_a_1_1_d_v_p.html", null ],
        [ "DynObstacleKDTreeProcessor", "class_nebukam_1_1_o_r_c_a_1_1_dyn_obstacle_k_d_tree_processor.html", null ],
        [ "DynObstacleProvider", "class_nebukam_1_1_o_r_c_a_1_1_dyn_obstacle_provider.html", null ],
        [ "IAgent", "interface_nebukam_1_1_o_r_c_a_1_1_i_agent.html", "interface_nebukam_1_1_o_r_c_a_1_1_i_agent" ],
        [ "IAgentGroup", "interface_nebukam_1_1_o_r_c_a_1_1_i_agent_group.html", null ],
        [ "IAgentKDTreeProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_agent_k_d_tree_provider.html", null ],
        [ "IAgentProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_agent_provider.html", null ],
        [ "IDynObstacleKDTreeProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_dyn_obstacle_k_d_tree_provider.html", null ],
        [ "IDynObstacleProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_dyn_obstacle_provider.html", null ],
        [ "IObstacleGroup", "interface_nebukam_1_1_o_r_c_a_1_1_i_obstacle_group.html", null ],
        [ "IObstacleKDTreeProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_obstacle_k_d_tree_provider.html", null ],
        [ "IObstacleProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_obstacle_provider.html", null ],
        [ "IORCALinesProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_o_r_c_a_lines_provider.html", null ],
        [ "IRaycastGroup", "interface_nebukam_1_1_o_r_c_a_1_1_i_raycast_group.html", null ],
        [ "IRaycastProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_raycast_provider.html", null ],
        [ "IStaticObstacleKDTreeProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_static_obstacle_k_d_tree_provider.html", null ],
        [ "IStaticObstacleProvider", "interface_nebukam_1_1_o_r_c_a_1_1_i_static_obstacle_provider.html", null ],
        [ "Obstacle", "class_nebukam_1_1_o_r_c_a_1_1_obstacle.html", "class_nebukam_1_1_o_r_c_a_1_1_obstacle" ],
        [ "ObstacleFixJob", "struct_nebukam_1_1_o_r_c_a_1_1_obstacle_fix_job.html", null ],
        [ "ObstacleFixProcessor", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_fix_processor.html", null ],
        [ "ObstacleGroup", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_group.html", null ],
        [ "ObstacleInfos", "struct_nebukam_1_1_o_r_c_a_1_1_obstacle_infos.html", null ],
        [ "ObstacleKDTreeBuilder", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_k_d_tree_builder.html", null ],
        [ "ObstacleKDTreeJob", "struct_nebukam_1_1_o_r_c_a_1_1_obstacle_k_d_tree_job.html", null ],
        [ "ObstacleKDTreeProcessor", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_k_d_tree_processor.html", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_k_d_tree_processor" ],
        [ "ObstacleOrientationJob", "struct_nebukam_1_1_o_r_c_a_1_1_obstacle_orientation_job.html", null ],
        [ "ObstacleOrientationProcessor", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_orientation_processor.html", null ],
        [ "ObstacleProvider", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_provider.html", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_provider" ],
        [ "ObstacleTreeNode", "struct_nebukam_1_1_o_r_c_a_1_1_obstacle_tree_node.html", null ],
        [ "ObstacleVertex", "class_nebukam_1_1_o_r_c_a_1_1_obstacle_vertex.html", null ],
        [ "ObstacleVertexData", "struct_nebukam_1_1_o_r_c_a_1_1_obstacle_vertex_data.html", null ],
        [ "ORCA", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a.html", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a" ],
        [ "ORCAApplyJob", "struct_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_apply_job.html", null ],
        [ "ORCAApplyProcessor", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_apply_processor.html", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_apply_processor" ],
        [ "ORCABundle", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_bundle.html", null ],
        [ "ORCALine", "struct_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_line.html", null ],
        [ "ORCALinesJob", "struct_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_lines_job.html", null ],
        [ "ORCALinesProcessor", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_lines_processor.html", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_lines_processor" ],
        [ "ORCAPreparation", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_preparation.html", "class_nebukam_1_1_o_r_c_a_1_1_o_r_c_a_preparation" ],
        [ "Raycast", "class_nebukam_1_1_o_r_c_a_1_1_raycast.html", null ],
        [ "RaycastData", "struct_nebukam_1_1_o_r_c_a_1_1_raycast_data.html", null ],
        [ "RaycastGroup", "class_nebukam_1_1_o_r_c_a_1_1_raycast_group.html", null ],
        [ "RaycastProvider", "class_nebukam_1_1_o_r_c_a_1_1_raycast_provider.html", "class_nebukam_1_1_o_r_c_a_1_1_raycast_provider" ],
        [ "RaycastResult", "struct_nebukam_1_1_o_r_c_a_1_1_raycast_result.html", null ],
        [ "RaycastsJob", "struct_nebukam_1_1_o_r_c_a_1_1_raycasts_job.html", null ],
        [ "RaycastsProcessor", "class_nebukam_1_1_o_r_c_a_1_1_raycasts_processor.html", "class_nebukam_1_1_o_r_c_a_1_1_raycasts_processor" ],
        [ "Segment2D", "struct_nebukam_1_1_o_r_c_a_1_1_segment2_d.html", "struct_nebukam_1_1_o_r_c_a_1_1_segment2_d" ],
        [ "StaticObstacleKDTreeProcessor", "class_nebukam_1_1_o_r_c_a_1_1_static_obstacle_k_d_tree_processor.html", null ],
        [ "StaticObstacleProvider", "class_nebukam_1_1_o_r_c_a_1_1_static_obstacle_provider.html", null ]
      ] ]
    ] ]
];